---
title: "Team 3 Forecasting Competition"
author: "Kristen Trinh, Jinxi Liu"
date: '2023-04-04'
output:
  html_document:
    df_print: paged
---

```{r message=FALSE, warning=FALSE}
#load library
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(zoo)
library(kableExtra)
library(readxl)
library(writexl)
```

```{r}
#loading the data
load_data<- read_excel(path="./data/load.xlsx",col_names=TRUE)
head(load_data)
```

```{r}
#average 24 hours data and combining with date
load_data_new<-load_data %>%
  select(h1:h24)
daily_load_mean<-rowMeans(load_data_new,c(3,26))
as.data.frame(daily_load_mean)

load_data_date<-load_data %>%
  select("date")

#creating variable to save this
daily_load_mean_date_df<-cbind.data.frame(load_data_date,daily_load_mean)

#filter to only 2005-2009
daily_load_mean_data_df_2009<-filter(daily_load_mean_date_df, date <= "2009-12-31")
```


```{r}
#creating time series object for just 2005-2009 data

ts_load_daily_2009 <- msts(daily_load_mean_data_df_2009$daily_load_mean, 
                          seasonal.periods =c(7,365.25),
                          start=c(2005,1,1))
```

```{r}
#decomposing data
ts_load_daily_2009 %>% mstl() %>%
  autoplot()

deseas_ts_load_daily_2009<-mstl(ts_load_daily_2009)
plot(deseas_ts_load_daily_2009)
```



```{r}
#create a subset for training purpose
n_for = 365
ts_load_daily_2009_train <- subset(ts_load_daily_2009,
                                   end = length(ts_load_daily_2009)-n_for)

#create a subset for testing purpose
ts_load_daily_2009_test <- subset(ts_load_daily_2009,
                                   start = length(ts_load_daily_2009)-n_for)

autoplot(ts_load_daily_2009_train)
autoplot(ts_load_daily_2009_test)
```


```{r}
#model ARIMA, non-seasonal

ARIMA_Four_fit <- auto.arima(ts_load_daily_2009_train, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(ts_load_daily_2009_train, 
                                          K=c(2,12))
                             )

#Forecast with ARIMA + Fourier
#also need to specify h for fourier terms
ARIMA_Four_for <- forecast(ARIMA_Four_fit,
                           xreg=fourier(ts_load_daily_2009_train,
                                        K=c(2,12),
                                        h=365),
                           h=365
                           ) 


deseas_ARIMA_load_daily_2009<-auto.arima(deseas_ts_load_daily_2009[,2], 
                                         )

deseas_ARIMA_forecast_load_daily_2009<-forecast(object=deseas_ARIMA_load_daily_2009, h=365)
plot(deseas_ARIMA_forecast_load_daily_2009)

```


```{r}
#model STL +ETS

#Fit and forecast STL + ETS model to data
ETS_fit <-  stlf(ts_load_daily_2009_train,h=365)

#Plot foresting results
autoplot(ETS_fit) + ylab("Daily Load")

#Plot model + observed data
autoplot(ts_load_daily_2009) +
  autolayer(ETS_fit, series="STL + ETS",PI=FALSE) +
  ylab("Daily Load")
```

```{r}
# plot ARIMA + FOURIER terms

#Plot foresting results
autoplot(ARIMA_Four_for) + ylab("Daily load")

#Plot model + observed data
autoplot(ts_load_daily_2009) +
  autolayer(ARIMA_Four_for, series="ARIMA_FOURIER",PI=FALSE) +
  ylab("Daily load")

```

```{r}
# Model: TBATS

# TBATS can take time to fit
TBATS_fit <- tbats(ts_load_daily_2009_train)

TBATS_for <- forecast(TBATS_fit, h=365)

#Plot foresting results
autoplot(TBATS_for) +
  ylab("Daily load") 

#Plot model + observed data

autoplot(ts_load_daily_2009) +
  autolayer(TBATS_for, series="TBATS",PI=FALSE)+
  ylab("Daily load") 

```

```{r}
# Model: Neural Network Time Series Forecasts

#NN_fit <- nnetar(ts_act_power_daily_train,p=1,P=1)
NN_fit <- nnetar(ts_load_daily_2009_train,p=1,P=0,xreg=fourier(ts_load_daily_2009_train, K=c(2,12)))

#NN_for <- forecast(NN_fit, h=365) 
NN_for <- forecast(NN_fit, h=365,xreg=fourier(ts_load_daily_2009_train, 
                                          K=c(2,12),h=365))

#Plot foresting results
autoplot(NN_for) +
  ylab("Daily load") 

#Plot model + observed data
autoplot(ts_load_daily_2009) +
  autolayer(NN_for, series="Neural Network",PI=FALSE)+
  ylab("Daily load") 

```

```{r}
## Checking accuracy of the models

ETS_scores <- accuracy(ETS_fit$mean,ts_load_daily_2009_test)  

#Model: ARIMA + Fourier 
ARIMA_scores <- accuracy(ARIMA_Four_for$mean,ts_load_daily_2009_test)

# Model:  TBATS 
TBATS_scores <- accuracy(TBATS_for$mean,ts_load_daily_2009_test)

# Model:  Neural Network 
NN_scores <- accuracy(NN_for$mean,ts_load_daily_2009_test)

```

```{r}
#Compare performance metrics

#create data frame
scores <- as.data.frame(
  rbind(ETS_scores, ARIMA_scores, TBATS_scores, NN_scores)
  )
row.names(scores) <- c("STL+ETS", "ARIMA+Fourier","TBATS","NN")

#choose model with lowest RMSE
best_model_index <- which.min(scores[,"RMSE"])
cat("The best model by RMSE is:", row.names(scores[best_model_index,]))  
```

```{r}
#create table to compare scores

kbl(scores, 
      caption = "Forecast Accuracy for Daily Load",
      digits = array(5,ncol(scores))) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "hold_position") %>%
  #highlight model with lowest RMSE
  kable_styling(latex_options="striped", stripe_index = which.min(scores[,"RMSE"]))
```


```{r}
#plot all models

autoplot(ts_load_daily_2009) +
  autolayer(ETS_fit, PI=FALSE, series="STL+ETS") +
  autolayer(ARIMA_Four_for, PI=FALSE, series="ARIMA + Fourier") +
  autolayer(TBATS_for,PI=FALSE, series="TBATS") +
  autolayer(NN_for,PI=FALSE, series="NN") +
  xlab("Day") + ylab("Daily Load") +
  guides(colour=guide_legend(title="Forecast"))
```

```{r}
#plot all models

autoplot(ts_load_daily_2009_test) +
  autolayer(ETS_fit, PI=FALSE, series="STL+ETS") +
  autolayer(ARIMA_Four_for, PI=FALSE, series="ARIMA + Fourier") +
  autolayer(TBATS_for,PI=FALSE, series="TBATS") +
  autolayer(NN_for,PI=FALSE, series="NN") +
  ylab("Daily Active Power") +
  guides(colour=guide_legend(title="Forecast"))
```
>: Based on the model results, ARIMA Fourier and TBATS are the best models to forecast for 2011

```{r}
#creating daily load mean data for 2010
daily_load_mean_data_df_2010<-filter(daily_load_mean_date_df, date <= "2010-12-31")

ts_load_daily_2010<-msts(daily_load_mean_data_df_2010$daily_load_mean, 
                          seasonal.periods =c(7,365.25),
                          start=c(2005,1,1))


ARIMA_Four_fit_2010 <- auto.arima(ts_load_daily_2010, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(ts_load_daily_2010, 
                                          K=c(2,12))
                             )

#Forecast with ARIMA fit
#also need to specify h for fourier terms
ARIMA_Four_for_2010 <- forecast(ARIMA_Four_fit_2010,
                           xreg=fourier(ts_load_daily_2010,
                                        K=c(2,12),
                                        h=365),
                           h=365
                           )
autoplot(ts_load_daily_2010) +
  autolayer(ARIMA_Four_for_2010, series="ARIMA Fourier",PI=FALSE)+
  ylab("Daily load") 


```

```{r}
#forecasting 2011 using TBAT model

TBATS_fit_2010 <- tbats(ts_load_daily_2010)

TBATS_for_2010 <- forecast(TBATS_fit_2010, h=365)

autoplot(ts_load_daily_2010) +
  autolayer(TBATS_for_2010, series="TBATS",PI=FALSE)+
  ylab("Daily load") 

```


```{r}
#creating data frame to submit for competition

TBATS_for_df<-as.data.frame(TBATS_for$mean)

ARIMA_Four_for_2010_df<-as.data.frame(ARIMA_Four_for_2010$mean)

TBATS_for_df_2010<-as.data.frame(TBATS_for_2010$mean)


```

